# Generated by Django 5.0.6 on 2024-07-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0002_rename_mbo_list_fcso_lists_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBO_list',
            fields=[
                ('pbo_cso_id', models.AutoField(primary_key=True, serialize=False)),
                ('pbo_cso_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pbo_cso_registered', models.DateTimeField(auto_now_add=True)),
                ('pbo_cso_vlidity', models.DateTimeField(blank=True, null=True)),
                ('pbo_cso_focal', models.CharField(blank=True, max_length=100, null=True)),
                ('pbo_cso_contact', models.CharField(blank=True, max_length=100)),
                ('pbo_cso_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('pbo_cso_url', models.URLField(blank=True, null=True)),
                ('pbo_cso_link', models.CharField(blank=True, max_length=200, null=True)),
                ('pbo_cso_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pbo_cso_status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PBO_lists',
        ),
    ]
