# Generated by Django 5.0.6 on 2024-07-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0003_pbo_list_delete_pbo_lists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PBO_list',
            new_name='PBO_lists',
        ),
    ]
