# Generated by Django 5.0.6 on 2024-07-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0004_rename_pbo_list_pbo_lists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MBO_lists',
            new_name='MBO_list',
        ),
    ]
