# Generated by Django 5.0.6 on 2024-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0006_rename_mbo_list_mbo_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcso_lists',
            name='fcso_cso_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fcso_lists',
            name='fcso_cso_validy',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mbo_lists',
            name='mbo_cso_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mbo_lists',
            name='mbo_cso_validy',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
