# Generated by Django 5.0.6 on 2024-07-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0007_alter_fcso_lists_fcso_cso_registered_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MBO_lists',
            new_name='MBO_list',
        ),
    ]
