# Generated by Django 5.0.6 on 2024-07-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0012_remove_fcso_lists_amendment_fee_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cso_fees_payment',
            name='fcso_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cso_app.fcso_lists'),
        ),
        migrations.AddField(
            model_name='fcso_lists',
            name='amendment_fee_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mbo_lists',
            name='amendment_fee_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pbo_lists',
            name='amendment_fee_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
