# Generated by Django 5.0.6 on 2024-07-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0013_cso_fees_payment_fcso_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSO_lists',
            fields=[
                ('cso_id', models.AutoField(primary_key=True, serialize=False)),
                ('cso_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cso_registered', models.DateTimeField(auto_now_add=True, null=True)),
                ('cso_validy', models.DateTimeField(auto_now=True, null=True)),
                ('cso_focal', models.CharField(blank=True, max_length=100, null=True)),
                ('cso_contact', models.CharField(blank=True, max_length=100)),
                ('cso_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cso_url', models.URLField(blank=True, null=True)),
                ('cso_link', models.CharField(blank=True, max_length=200, null=True)),
                ('cso_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cso_type', models.CharField(blank=True, max_length=100, null=True)),
                ('renewal_fee_due_date', models.DateTimeField(blank=True, null=True)),
                ('late_renewal_fee_due_date', models.DateTimeField(blank=True, null=True)),
                ('amendment_fee_due_date', models.DateTimeField(blank=True, null=True)),
                ('registration_fee_due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cso_fees_payment',
            name='fcso_id',
        ),
        migrations.RemoveField(
            model_name='cso_fees_payment',
            name='mbo_id',
        ),
        migrations.RemoveField(
            model_name='cso_fees_payment',
            name='pbo_id',
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='cso_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cso_app.cso_lists'),
        ),
        migrations.DeleteModel(
            name='FCSO_lists',
        ),
        migrations.DeleteModel(
            name='MBO_lists',
        ),
        migrations.DeleteModel(
            name='PBO_lists',
        ),
    ]
