# Generated by Django 5.0.6 on 2024-07-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0017_rename_cso_registered_cso_lists_cso_registered_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cso_lists',
            old_name='cso_validy_date',
            new_name='cso_validity_date',
        ),
    ]
