# Generated by Django 5.0.6 on 2024-07-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0018_rename_cso_validy_date_cso_lists_cso_validity_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cso_fees_payment',
            old_name='renewal_fees',
            new_name='account_number',
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='amendment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='bank_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='user_cid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
