# Generated by Django 5.0.6 on 2024-07-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0019_rename_renewal_fees_cso_fees_payment_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cso_fees_payment',
            old_name='amendment_fees',
            new_name='fees_payment_type',
        ),
        migrations.RenameField(
            model_name='cso_fees_payment',
            old_name='registration_fees',
            new_name='mobile_number',
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
