# Generated by Django 5.0.6 on 2024-07-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0021_cso_fees_payment_amendment_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cso_fees_payment',
            name='payment_screenshot',
        ),
    ]
