# Generated by Django 5.0.6 on 2024-07-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0022_remove_cso_fees_payment_payment_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cso_fees_payment',
            name='payment_type',
        ),
    ]
