# Generated by Django 5.0.6 on 2024-07-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0024_cso_fees_payment_overall_fines'),
    ]

    operations = [
        migrations.AddField(
            model_name='cso_fees_payment',
            name='days_fine',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
