# Generated by Django 5.0.6 on 2024-07-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0025_cso_fees_payment_days_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cso_fees_payment',
            name='days_fine',
        ),
    ]
