# Generated by Django 5.0.6 on 2024-07-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0027_cso_fees_payment_cso_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cso_fees_payment',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
