# Generated by Django 5.0.6 on 2024-07-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0028_cso_fees_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cso_fees_payment',
            name='reject_reasons',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
