# Generated by Django 5.0.6 on 2024-07-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0030_cso_fees_payment_annual_general_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cso_fees_payment',
            name='annual_general_report',
        ),
        migrations.RemoveField(
            model_name='cso_fees_payment',
            name='annual_report',
        ),
        migrations.RemoveField(
            model_name='cso_fees_payment',
            name='audit_report',
        ),
        migrations.RemoveField(
            model_name='cso_fees_payment',
            name='two_yrs_report',
        ),
    ]
