# Generated by Django 5.0.6 on 2024-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0031_remove_cso_fees_payment_annual_general_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cso_fees_payment',
            name='annual_general_report',
            field=models.FileField(default=1, upload_to='annual_general_report/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='annual_report',
            field=models.FileField(default=1, upload_to='annual_report/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='audit_report',
            field=models.FileField(default=1, upload_to='audit_report/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cso_fees_payment',
            name='two_yrs_report',
            field=models.FileField(default=1, upload_to='two_yrs_report/'),
            preserve_default=False,
        ),
    ]
