# Generated by Django 5.0.6 on 2024-07-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0032_cso_fees_payment_annual_general_report_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cso_fees_payment',
        ),
    ]
