# Generated by Django 5.0.6 on 2024-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0034_cso_fees_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_fees_payment',
            name='overall_fines',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
