# Generated by Django 5.0.6 on 2024-07-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0036_alter_cso_fees_payment_annual_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_fees_payment',
            name='annual_report',
            field=models.FileField(blank=True, null=True, upload_to='annual_report/'),
        ),
    ]
