# Generated by Django 5.0.6 on 2024-07-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0037_alter_cso_fees_payment_annual_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_fees_payment',
            name='annual_general_report',
            field=models.FileField(blank=True, default='annual_general_report/index.html', null=True, upload_to='annual_general_report/'),
        ),
    ]
