# Generated by Django 5.0.6 on 2024-07-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0042_cso_fees_payment_journal_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cso_types',
            old_name='cso_name',
            new_name='cso_type_name',
        ),
    ]
