# Generated by Django 5.0.6 on 2024-07-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0045_cso_lists_address_cso_lists_cso_focal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_lists',
            name='cso_focal_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cso_lists',
            name='executive_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cso_lists',
            name='public_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
