# Generated by Django 5.0.6 on 2024-07-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0046_alter_cso_lists_cso_focal_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('appointed_date', models.DateField()),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('other_trusteeship', models.TextField(blank=True, null=True)),
                ('cso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustees', to='cso_app.cso_lists')),
            ],
        ),
    ]
