# Generated by Django 5.0.6 on 2024-07-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0047_trustee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustee',
            name='appointed_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
