# Generated by Django 5.0.6 on 2024-07-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0048_alter_trustee_appointed_date_alter_trustee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_lists',
            name='po_box',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
