# Generated by Django 5.0.6 on 2024-07-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0050_alter_cso_lists_operation_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_lists',
            name='fax',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
