# Generated by Django 5.0.6 on 2024-07-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0052_alter_cso_lists_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cso_lists',
            old_name='pubic_email',
            new_name='public_email',
        ),
    ]
