# Generated by Django 5.0.6 on 2024-08-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0054_alter_trustee_appointed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_lists',
            name='cso_validity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
