# Generated by Django 5.0.6 on 2024-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0055_alter_cso_lists_cso_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_roles',
            name='user_role_full',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
