# Generated by Django 5.0.6 on 2024-08-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0059_alter_users_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cso_lists',
            name='amendment_fee_due_date',
        ),
    ]
