# Generated by Django 5.0.6 on 2024-08-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0060_remove_cso_lists_amendment_fee_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='financial_attachments',
            fields=[
                ('financial_attachments_id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_attachments_name', models.CharField(blank=True, max_length=200, null=True)),
                ('financial_description', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment_cso_type', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment_public_display', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment_status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='financial_class',
            fields=[
                ('financial_id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_class', models.CharField(blank=True, max_length=200, null=True)),
                ('financial_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='financial_group',
            fields=[
                ('financial_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('financial_description', models.CharField(blank=True, max_length=200, null=True)),
                ('financial_group_class', models.CharField(blank=True, max_length=200, null=True)),
                ('financial_group_status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
