# Generated by Django 5.0.6 on 2024-08-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0063_cso_lists_invalid_certificate_fines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_lists',
            name='invalid_certificate_fines',
            field=models.CharField(blank=True, default='0', max_length=1000, null=True),
        ),
    ]
