# Generated by Django 5.0.6 on 2024-08-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0067_cso_fees_payment_amendment_fees_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cso_fees_payment',
            new_name='cso_attachment_and_fees',
        ),
    ]
