# Generated by Django 5.0.6 on 2024-08-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0068_rename_cso_fees_payment_cso_attachment_and_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_attachment_and_fees',
            name='cso_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
