# Generated by Django 5.0.6 on 2024-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0070_cso_attachment_and_fees_delayed_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_attachment_and_fees',
            name='amendment_fees',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
