# Generated by Django 5.0.6 on 2024-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0071_alter_cso_attachment_and_fees_amendment_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_attachment_and_fees',
            name='overall_fines',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
