# Generated by Django 5.0.6 on 2024-08-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0073_alter_cso_attachment_and_fees_overall_fines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso_attachment_and_fees',
            name='annual_general_report',
            field=models.FileField(blank=True, default='annual_general_report/bg_astronaut.jpg', null=True, upload_to='annual_general_report/'),
        ),
    ]
