# Generated by Django 5.0.6 on 2024-08-16 03:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0079_cso_attachment_and_fees_payment_advice_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('notifications_id', models.UUIDField(default=uuid.UUID('cf2c7cb4-4956-4ac5-90c3-46cabe07adb6'), editable=False, primary_key=True, serialize=False)),
                ('notification_title', models.CharField(blank=True, max_length=200, null=True)),
                ('notification_content', models.CharField(blank=True, max_length=200, null=True)),
                ('notification_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
