# Generated by Django 5.0.6 on 2024-08-16 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0080_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_view',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('ba0f7dd8-7e7c-404c-8f32-9661e065d25b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
