# Generated by Django 5.0.6 on 2024-08-16 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0081_notifications_notification_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('b9cc49ac-69cc-4620-a18c-d2393eb2cf78'), editable=False, primary_key=True, serialize=False),
        ),
    ]
