# Generated by Django 5.0.6 on 2024-08-16 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0082_notifications_notification_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_orgs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('c2522ea6-9375-4de4-a3c0-77242743d34d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
