# Generated by Django 5.0.6 on 2024-08-21 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0083_notifications_notification_orgs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('33aff322-e541-44b7-945e-45cc3a38c678'), editable=False, primary_key=True, serialize=False),
        ),
    ]
