# Generated by Django 5.0.6 on 2024-08-22 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0085_alter_notifications_notifications_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.UUIDField(default=uuid.UUID('50bea2c8-94e4-4079-9440-e9d7cde8371f'), editable=False, unique=True)),
                ('post_header', models.CharField(blank=True, max_length=225, null=True)),
                ('activity', models.CharField(blank=True, max_length=225, null=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=225, null=True)),
                ('featured', models.CharField(blank=True, max_length=225, null=True)),
                ('attachments', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('7bf28f2c-2cf0-4140-b3b1-f657846a81a7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
