# Generated by Django 5.0.6 on 2024-08-22 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0086_post_publish_alter_notifications_notifications_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('32d730d0-6a51-4a32-ac78-1f3cbff5bbd2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post_publish',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('8fd1cedc-4878-4ae0-ae95-ba1327c0b405'), editable=False, unique=True),
        ),
    ]
