# Generated by Django 5.0.6 on 2024-08-26 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0088_post_publish_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('b9747016-0296-4b08-96c7-22e2aececbb1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post_publish',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('d10dca3e-ca9b-4472-ae29-40b15e73b092'), editable=False, unique=True),
        ),
    ]
