# Generated by Django 5.0.6 on 2024-08-26 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0089_alter_notifications_notifications_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_publish',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('2f660dec-7a01-4add-af82-7fdde7029d67'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post_publish',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('69e7cc8f-ea74-47eb-a6af-076ad5d8c78d'), editable=False, unique=True),
        ),
    ]
