# Generated by Django 5.0.6 on 2024-09-19 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0093_alter_notifications_notifications_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('ed21f865-dff1-4225-9532-50184d8537a0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page_contents',
            name='content_id',
            field=models.UUIDField(default=uuid.UUID('8e554316-1d88-49f0-bb80-6637d84a1297'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post_publish',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('339c4d72-2a68-49bf-845e-41c4540dc62d'), editable=False, unique=True),
        ),
    ]
