# Generated by Django 5.0.6 on 2024-09-19 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0094_alter_notifications_notifications_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('ae761077-978f-407d-88fc-fa3bb7bf402a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page_contents',
            name='content_id',
            field=models.UUIDField(default=uuid.UUID('0f5b2afb-6148-447d-8546-82fde9bbbcdf'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post_publish',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('05aa8f88-25e9-4f72-a0a8-cc25f4c0e15b'), editable=False, unique=True),
        ),
    ]
