# Generated by Django 5.0.6 on 2024-09-19 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0096_alter_notifications_notifications_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('0b917e70-adb9-4c97-b02d-330ccde36853'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page_contents',
            name='content_id',
            field=models.UUIDField(default=uuid.UUID('84cc3f5d-7bda-4cbf-a3b1-2a8be1c90803'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post_publish',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('063bfac7-f93c-482c-85e6-5a542573b0c6'), editable=False, unique=True),
        ),
    ]
