# Generated by Django 5.0.6 on 2024-09-24 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_app', '0097_alter_notifications_notifications_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_publish',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notifications_id',
            field=models.UUIDField(default=uuid.UUID('39711d7a-321e-49af-b323-8ae6a12b5bc0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page_contents',
            name='content_id',
            field=models.UUIDField(default=uuid.UUID('26df190c-d000-4c1a-ad4f-38239019a93a'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post_publish',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('d17cbb0b-c9de-499a-a755-003796563077'), editable=False, unique=True),
        ),
    ]
